---

# Application settings.
virtualenv_path: "/virtualenv/{{ application_name }}"
project_dir: "/var/{{ project_name }}"
log_dir: "{{ project_dir }}/logs"
gunicorn_log_file: "{{ log_dir }}/gunicorn/gunicorn_supervisor.log"
webapp_dir: "{{ project_dir }}/webapp"
source_dir: "{{ project_dir }}/source_repo"
requirements_file: "{{ source_dir }}/requirements/development.txt"

# Gunicorn settings
gunicorn_user: "{{ application_name  }}"
gunicorn_group: webapps


# Nginx settings
nginx_http_port: 80
nginx_https_port: 443
nginx_access_log_file: "{{ log_dir  }}/nginx/nginx_access.log"
nginx_error_log_file: "{{ log_dir  }}/nginx/nginx_error.log"
nginx_static_dir: "{{ webapp_dir  }}/static/"
nginx_media_dir: "{{ webapp_dir  }}/media/"

# Django Environment variables
django_environment:
  DJANGO_SETTINGS_MODULE: "{{ django_settings_file }}"
  DJANGO_SECRET_KEY: "{{ django_secret_key }}"
  MEDIA_ROOT: "{{ nginx_media_dir }}"
  STATIC_ROOT: "{{ nginx_static_dir }}"
  DATABASE_USER: "{{ db_user }}"
  DATABASE_PASSWORD: "{{ db_password }}"
  EMAIL_HOST: "{{ email_host|default(omit) }}"
  EMAIL_HOST_USER: "{{ email_host_user|default(omit) }}"
  EMAIL_HOST_PASSWORD: "{{ email_host_password|default(omit) }}"
  BROKER_URL: "{{ broker_url|default(omit) }}"
