---

- name: Create the application user
  user: name={{ sys_user }} state=present

- name: Create the application group
  group: name={{ sys_group }} system=yes state=present

- name: Add the application user to the application group
  user: name={{ sys_user }} group={{ sys_group }} state=present
