---

- name: Create the Supervisor config file
  template: src=supervisor_config.jinja
            dest=/etc/supervisor/conf.d/{{ application_name }}.conf
            backup=yes

- name: Start supervisor
  become: yes
  become_user: root
  service: name=supervisor state=started

- name: Re-read the Supervisor config files
  become: yes
  become_user: root
  supervisorctl: name={{ application_name }} state=present

- name: Restart Supervisor
  become: yes
  become_user: root
  supervisorctl: name={{ application_name }} state=restarted
