- name: Creates directory
  file: path="{{ project_dir }}" state=directory

- name: Setup the Git repo
  git: repo={{ git_repo }}
       version="{{ git_branch }}"
       dest="{{ source_dir }}"
       accept_hostkey=yes
  tags: git

- name: Delete all .pyc files
  command: find . -name '*.pyc' -delete
  args:
    chdir: "{{ webapp_dir }}"
  tags: git

