---

- name: Install packages required by the Django app inside virtualenv
  become: yes
  become_user: root
  pip: virtualenv={{ virtualenv_path }} requirements={{ requirements_file }}

- name: Run Django database migrations
  django_manage:
    command: migrate
    app_path: "{{ webapp_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  environment: "{{ django_environment }}"
  when: run_django_db_migrations is defined and run_django_db_migrations
  tags: django.migrate

- name: Run Django collectstatic
  django_manage:
    command: collectstatic
    app_path: "{{ webapp_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  environment: "{{ django_environment }}"
  when: run_django_collectstatic is defined and run_django_collectstatic
  tags: django.collectstatic

- name: Run Django loaddata
  django_manage:
    command: loaddata helpers/admin_fixture.json
    app_path: "{{ webapp_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  environment: "{{ django_environment }}"
  when: run_django_loaddata is defined and run_django_loaddata
  tags: django.loaddata
