---

- name: Create the Supervisor config file
  template: src=supervisor_config.jinja
            dest=/etc/supervisor/conf.d/{{ application_name }}.conf
            backup=yes

- name: Re-read the Supervisor config files
  sudo: yes
  sudo_user: root
  supervisorctl: name={{ application_name }} state=present

- name: Restart Supervisor
  sudo: yes
  sudo_user: root
  supervisorctl: name={{ application_name }} state=restarted
