---

- name: Provision a {{ project_name }} db server
  # become: yes
  # become_user: root
  hosts: dbservers
  # remote_user: root
  vars:
    - update_apt_cache: yes
  vars_files:
    - group_vars/base.yml
    - group_vars/{{ env }}.yml

  roles:
    - db
