# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20151228_0429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='seed',
        ),
    ]
