# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20151229_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemmapping',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Problem'),
        ),
    ]
