# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 00:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20151230_0634'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='answer',
            table='answers',
        ),
    ]
