# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-22 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20161124_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemmapping',
            name='assignment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Assignment'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ProblemMapping'),
        ),
    ]
