# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-25 23:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20171122_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Assignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assignment_mappings',
            },
        ),
        migrations.RemoveField(
            model_name='problemmapping',
            name='assignment_id',
        ),
        migrations.AddField(
            model_name='problemmapping',
            name='assignment_mapping_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.AssignmentMapping'),
        ),
        migrations.AddField(
            model_name='user',
            name='assignments',
            field=models.ManyToManyField(through='core.AssignmentMapping', to='core.Assignment'),
        ),
    ]
