# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-26 00:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20171125_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='problem',
            new_name='problem_mapping',
        ),
    ]
