# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-26 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20171126_0109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='problem_mapping_id',
            new_name='problem_mapping',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='assignmentmapping',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='problemmapping',
            old_name='assignment_mapping_id',
            new_name='assignment_mapping',
        ),
        migrations.RenameField(
            model_name='problemmapping',
            old_name='problem_id',
            new_name='problem',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='assignment',
            new_name='assignments',
        ),
    ]
