# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-08 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20171126_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='library_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='value',
            field=models.TextField(null=True),
        ),
    ]
